app:
  security:
    routes:
      public-routes:
        - pattern: /api/health
      secure-routes:
        - pattern: /api/admin/**
          role: ADMIN
        - pattern: /api/**            # authenticated-only (no role)
    jwt:
      issuer: "https://example-issuer"          # optional validation hint
      hmac-secret: "${JWT_SECRET:change-me}"    # provide via env in deploy/local
      authorities-claim: "roles"                # array claim to map -> ROLE_*
