

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/demo_db}
    username: ${DB_USERNAME:demo}
    password: ${DB_PASSWORD:demo}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: MANUAL
        prefetch: 10
        concurrency: 2


management:
  endpoint:
    health:
      show-details: "always"

logging:
  level:
    com.example: DEBUG

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:GroupNine}
      hmac-secret: "${JWT_SECRET:change-me}"
      authorities-claim: ${JWT_AUTHORITIES_CLAIM:roles}
    bruteforce:
      email-max: ${BRUTEFORCE_EMAIL_MAX:10}
      ip-max: ${BRUTEFORCE_IP_MAX:50}
      window-seconds: ${BRUTEFORCE_WINDOW_SECONDS:900}
      key-prefix: "${BRUTEFORCE_KEY_PREFIX:app:}"
      backoff-base-seconds: ${BRUTEFORCE_BACKOFF_BASE_SECONDS:60}
      backoff-factor: ${BRUTEFORCE_BACKOFF_FACTOR:2.0}
      backoff-max-seconds: ${BRUTEFORCE_BACKOFF_MAX_SECONDS:3600}
  auth:
    refresh-ttl-days: ${REFRESH_TOKEN_TTL_DAYS:14}
    refresh-cookie-name: ${REFRESH_TOKEN_COOKIE_NAME:refreshToken}
  flyway:
    repair-on-start: true

email:
  worker:
    enabled: ${EMAIL_WORKER_ENABLED:true}

mailjet:
  apiKey: ${MAILJET_API_KEY:}
  apiSecret: ${MAILJET_API_SECRET:}
  from:
    email: ${MAIL_FROM_EMAIL:no-reply@jakubolszewski.dev}
    name: ${MAIL_FROM_NAME:GroupNine}

server:
  port: ${PORT:8080}

