server:
  port: 8080

spring:
  application:
    name: backend
  main:
    banner-mode: "console"
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: MANUAL
        prefetch: 10
        concurrency: 2
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/demo_db}
    username: ${DB_USERNAME:demo}
    password: ${DB_PASSWORD:demo}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: "never"

logging:
  level:
    root: INFO
    com.example: INFO

app:
  security:
    routes:
      public-routes:
        - pattern: /api/health
        - pattern: /dev/**
        - pattern: /**/auth/**
        - pattern: /api/v1/auth/**
      secure-routes:
        - pattern: /api/admin/**
          role: ADMIN
        - pattern: /api/**
    jwt:
      issuer: "https://example-issuer"
      hmac-secret: "${JWT_SECRET:change-me}"
      authorities-claim: "roles"
  base-url: "http://localhost:3000"
  email:
    from: "no-reply@example.com"
    enabled: true
  auth:
    refresh-ttl-days: 14
    refresh-cookie-name: refreshToken

email:
  worker:
    enabled: true

mailjet:
  apiKey: ${MAILJET_API_KEY:}
  apiSecret: ${MAILJET_API_SECRET:}
  from:
    email: ${MAIL_FROM_EMAIL:no-reply@example.com}
    name: ${MAIL_FROM_NAME:GroupNine}
