services:
  swe-backend-green:
    image: ghcr.io/olszewski-jakub/stackoverflowedcup-api:backend-deploy-test
    container_name: swe-backend-green
    entrypoint: ["java","-jar","/app/app.jar","--spring.profiles.active=deploy"]
    # load variables from repo root .env
    env_file:
      - ../.env
    environment:
      SPRING_PROFILES_ACTIVE: "deploy"

      PORT: 8888

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUTHORITIES_CLAIM: ${JWT_AUTHORITIES_CLAIM}

      # Refresh token
      REFRESH_TOKEN_TTL_DAYS: ${REFRESH_TOKEN_TTL_DAYS}
      REFRESH_TOKEN_COOKIE_NAME: ${REFRESH_TOKEN_COOKIE_NAME}

      # Database
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_MAX_POOL_SIZE: ${DB_MAX_POOL_SIZE}

      # Redis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}

      # RabbitMQ
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      # Mailjet / mail
      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_API_SECRET: ${MAILJET_API_SECRET}
      MAIL_FROM_EMAIL: ${MAIL_FROM_EMAIL}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

      # Feature toggles
      EMAIL_WORKER_ENABLED: ${EMAIL_WORKER_ENABLED}

      # Brute force protection
      BRUTEFORCE_EMAIL_MAX: ${BRUTEFORCE_EMAIL_MAX}
      BRUTEFORCE_IP_MAX: ${BRUTEFORCE_IP_MAX}
      BRUTEFORCE_WINDOW_SECONDS: ${BRUTEFORCE_WINDOW_SECONDS}
      BRUTEFORCE_KEY_PREFIX: ${BRUTEFORCE_KEY_PREFIX}
      BRUTEFORCE_BACKOFF_BASE_SECONDS: ${BRUTEFORCE_BACKOFF_BASE_SECONDS}
      BRUTEFORCE_BACKOFF_FACTOR: ${BRUTEFORCE_BACKOFF_FACTOR}
      BRUTEFORCE_BACKOFF_MAX_SECONDS: ${BRUTEFORCE_BACKOFF_MAX_SECONDS}

    ports:
      - "8888:8888"
    networks:
      - bushive_network
    restart: unless-stopped

  swe-backend-blue:
    image: ghcr.io/olszewski-jakub/stackoverflowedcup-api:backend-deploy-test
    container_name: swe-backend-blue
    entrypoint: ["java","-jar","/app/app.jar","--spring.profiles.active=deploy"]
    # load variables from repo root .env
    env_file:
      - ../.env
    environment:
      SPRING_PROFILES_ACTIVE: "deploy"

      PORT: 8889

      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUTHORITIES_CLAIM: ${JWT_AUTHORITIES_CLAIM}

      REFRESH_TOKEN_TTL_DAYS: ${REFRESH_TOKEN_TTL_DAYS}
      REFRESH_TOKEN_COOKIE_NAME: ${REFRESH_TOKEN_COOKIE_NAME}

      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_MAX_POOL_SIZE: ${DB_MAX_POOL_SIZE}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      MAILJET_API_KEY: ${MAILJET_API_KEY}
      MAILJET_API_SECRET: ${MAILJET_API_SECRET}
      MAIL_FROM_EMAIL: ${MAIL_FROM_EMAIL}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}

      EMAIL_WORKER_ENABLED: ${EMAIL_WORKER_ENABLED}

      BRUTEFORCE_EMAIL_MAX: ${BRUTEFORCE_EMAIL_MAX}
      BRUTEFORCE_IP_MAX: ${BRUTEFORCE_IP_MAX}
      BRUTEFORCE_WINDOW_SECONDS: ${BRUTEFORCE_WINDOW_SECONDS}
      BRUTEFORCE_KEY_PREFIX: ${BRUTEFORCE_KEY_PREFIX}
      BRUTEFORCE_BACKOFF_BASE_SECONDS: ${BRUTEFORCE_BACKOFF_BASE_SECONDS}
      BRUTEFORCE_BACKOFF_FACTOR: ${BRUTEFORCE_BACKOFF_FACTOR}
      BRUTEFORCE_BACKOFF_MAX_SECONDS: ${BRUTEFORCE_BACKOFF_MAX_SECONDS}

    ports:
      - "8889:8889"
    networks:
      - bushive_network
    restart: unless-stopped

networks:
  bushive_network:
    external: true
