name: Monorepo CI Umbrella


on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Paths filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/deploy-backend.yml'
            frontend:
              - 'frontend/**'
              - '.github/workflows/deploy-frontend.yml'

  backend:
    name: Backend Pipeline
    needs: [ changes ]
    if: needs.changes.outputs.backend == 'true'
    uses: .github/workflows/deploy-backend.yml
    secrets: inherit

  frontend:
    name: Frontend Pipeline
    needs: [ changes ]
    if: needs.changes.outputs.frontend == 'true'
    uses: .github/workflows/deploy-frontend.yml
    secrets: inherit

