name: Pull Request Umbrella

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
  security-events: write
  packages: read

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Paths filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/backend-pr.yml'
            frontend:
              - 'frontend/**'
              - '.github/workflows/frontend.yml'

  backend:
    name: Backend PR Pipeline
    needs: [ changes ]
    if: needs.changes.outputs.backend == 'true'
    uses: ./.github/workflows/backend-pr.yml
    secrets: inherit

  frontend:
    name: Frontend PR Pipeline
    needs: [ changes ]
    if: needs.changes.outputs.frontend == 'true'
    uses: ./.github/workflows/frontend.yml
    secrets: inherit

