name: Frontend PR Pipeline

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  build_app:
    name: Build App
    runs-on: ubuntu-latest
    outputs:
      build_success: ${{ steps.build_status.outputs.success }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build app
        id: build_status
        working-directory: frontend
        run: |
          set -e
          npm run build
          echo "success=true" >> "$GITHUB_OUTPUT"

      - name: Upload build artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build
          retention-days: 1

  prepare_vercel_artifacts:
    name: Prepare Vercel Artifacts
    runs-on: ubuntu-latest
    needs: build_app
    if: needs.build_app.outputs.build_success == 'true'
    outputs:
      prebuilt_path: ${{ steps.save.outputs.path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Environment Info (preview)
        working-directory: frontend
        run: vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"

      - name: Build Prebuilt Bundle
        working-directory: frontend
        run: vercel build --token="$VERCEL_TOKEN"

      - name: Upload Prebuilt Bundle
        id: save
        uses: actions/upload-artifact@v4
        with:
          name: vercel-prebuilt
          path: frontend/.vercel/output
          retention-days: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_preview:
    name: Deploy to Vercel (Preview)
    runs-on: ubuntu-latest
    needs: prepare_vercel_artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Download Prebuilt Bundle
        uses: actions/download-artifact@v4
        with:
          name: vercel-prebuilt
          path: frontend/.vercel/output

      - name: Deploy to Vercel
        id: deploy
        working-directory: frontend
        shell: bash
        run: |
          url="$(vercel deploy --prebuilt --token="$VERCEL_TOKEN" | tail -n1)"
          echo "preview_url=$url" >> "$GITHUB_OUTPUT"

      - name: Comment Preview URL on PR
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "✅ Vercel Preview ready: ${{ steps.deploy.outputs.preview_url }}"
